#!/bin/sh

set -eu

z40=0000000000000000000000000000000000000000

echo "Searching for secrets in commits..."
while read -r oldrev newrev refname; do

    # Handle deleted branches
    if [ "$newrev" = $z40 ]
    then
        continue
    fi

    # For new branches, use the merge base with the main branch. If the new
    # branch is completely independent of the main branch, we just have to check
    # all commits.
    base="$oldrev"
    if [ "$oldrev" = $z40 ]
    then
        echo "newbranch"
        base=$(git merge-base HEAD $newrev || git rev-list --max-parents=0 $newrev)
    fi

    /var/opt/gitlab/gitaly/hooks-bin/secrecy.py between $base $newrev
done
